name: Install dependencies
inputs:
  cxx_flags:
    required: false
  cxx_linker_flags:
    required: false
  build_type:
    required: true
  msvc_runtime_library:
    required: true

outputs:
  BOOST_ROOT:
    value: ${{ steps.install_boost.outputs.BOOST_ROOT }}
    
runs:
  using: composite        
  steps:
    - name: Install dependencies
      shell: cmd
      run: |
        cd ..
        
        # install glm
        git clone https://github.com/g-truc/glm.git
        
        # install gtest
        git clone https://github.com/google/googletest.git
        cd googletest
        mkdir build
        cd build
        cmake .. -DCMAKE_CXX_FLAGS="${{ inputs.cxx_flags }}" -DCMAKE_EXE_LINKER_FLAGS="${{ inputs.cxx_linker_flags }}" -DCMAKE_MSVC_RUNTIME_LIBRARY="${{ inputs.msvc_runtime_library }}"
        cmake --build .  --config ${{ inputs.build_type }} -j %NUMBER_OF_PROCESSORS%
        cd ..
        cd ..
    - name: Install boost
      uses: MarkusJx/install-boost@v2.4.1
      id: install_boost
      with:
        boost_version: 1.81.0