name: Install dependencies
inputs:
  build_type:
    required: true
outputs:
  BOOST_ROOT:
    value: ${{ steps.install_boost.outputs.BOOST_ROOT }}
    
runs:
  using: composite        
  steps:
    - name: Install dependencies
      shell: cmd
      run: |
        cd ..
        
        # install glm
        git clone https://github.com/g-truc/glm.git
        
        # install gtest
        git clone https://github.com/google/googletest.git
        cd googletest
        mkdir build
        cd build
        cmake ..
        cmake --build .  --config ${{ inputs.build_type }} -j %NUMBER_OF_PROCESSORS%
        cd ..
        cd ..
    - name: Install boost
      uses: MarkusJx/install-boost@v2.4.1
      id: install_boost
      with:
        boost_version: 1.79.0