name: Install dependencies
inputs:
  build_type:
    required: true

runs:
  using: composite        
  steps:
    - name: Install dependencies
      shell: cmd
      run: |
        cd ..
        
        # install glm
        git clone https://github.com/g-truc/glm.git
        
        # install gtest
        git clone https://github.com/google/googletest.git
        cd googletest
        mkdir build
        cd build
        cmake ..
        cmake --build .  --config ${{ inputs.build_type }} -j %NUMBER_OF_PROCESSORS%
        cd ..
        cd ..