image: Visual Studio 2019

init:
  - git config --global core.autocrlf input

clone_folder: c:\projects\qxLib
shallow_clone: true

matrix:
  fast_finish: false

platform:
  - x64
  - x86

configuration:
  - Debug
  - Release

build_script:
  - cd ..
  
  # install glm
  - git clone https://github.com/g-truc/glm.git
  
  # install gtest
  - git clone https://github.com/google/googletest.git
  - cd googletest
  - mkdir build
  - cd build
  - cmake .. %CMAKE_CONFIGURE_FLAGS%
  - cmake --build . %CMAKE_BUILD_FLAGS%
  - cd ..
  - cd ..
  
  # install qxLib
  - cd qxLib
  - mkdir build
  - cd build
  - cmake -DGENERATE_TESTS=1 .. %CMAKE_CONFIGURE_FLAGS%
  - cmake --build . %CMAKE_BUILD_FLAGS% -j %NUMBER_OF_PROCESSORS%
  - ctest --output-on-failure -j %NUMBER_OF_PROCESSORS%