name: Run tests

runs:
  using: composite
  steps:
    - name: Run tests
      shell: cmd
      working-directory: build
      run: |
        ctest --output-on-failure -j %NUMBER_OF_PROCESSORS%
