name: Install dependencies
inputs:
  build_type:
    required: true

runs:
  using: composite        
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        # gtest 1.10
        sudo wget https://github.com/google/googletest/archive/release-1.10.0.tar.gz
        tar xf release-1.10.0.tar.gz
        cd googletest-release-1.10.0
        cmake . -DCMAKE_BUILD_TYPE=${{ inputs.build_type }}
        cmake --build . -j $(nproc)
        sudo cp -a googletest/include/gtest /usr/local/include
        sudo cp -a lib/*.a /usr/local/lib/
        cd ..  
        rm -r googletest-release-1.10.0
        rm release-1.10.0.tar.gz
        
        # glm
        if [ "$RUNNER_OS" = "Linux" ]; then
          sudo apt-get install libglm-dev;
        elif [ "$RUNNER_OS" = "macOS" ]; then
          brew install glm;
        fi  
