name: Install dependencies
inputs:
  cxx_flags:
    required: false
  cxx_linker_flags:
    required: false
  build_type:
    required: true
  
outputs:
  BOOST_ROOT:
    value: ${{ steps.install_boost.outputs.BOOST_ROOT }}

runs:
  using: composite
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        if [ "$RUNNER_OS" = "Linux" ]; then
          sudo apt-get remove libgtest-dev
          sudo apt-get install cmake git build-essential
          git clone https://github.com/google/googletest.git
          cd googletest
          mkdir build && cd build
          cmake .. -DCMAKE_CXX_STANDARD=20 -DCMAKE_CXX_STANDARD_REQUIRED=ON
          make -j$(nproc)
          sudo make install

          sudo apt-get install libglm-dev;
        elif [ "$RUNNER_OS" = "macOS" ]; then
          brew install googletest;
          brew install glm;
        fi
    - name: Install boost
      uses: MarkusJx/install-boost@main
      id: install_boost
      with:
        boost_version: 1.81.0