name: Install dependencies
inputs:
  cxx_flags:
    required: false
  cxx_linker_flags:
    required: false
  build_type:
    required: true
  
outputs:
  BOOST_ROOT:
    value: ${{ steps.install_boost.outputs.BOOST_ROOT }}

runs:
  using: composite        
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        if [ "$RUNNER_OS" = "Linux" ]; then
          sudo apt-get install libgtest-dev;
          sudo apt-get install libglm-dev;
        elif [ "$RUNNER_OS" = "macOS" ]; then
          brew install googletest;
          brew install glm;
        fi
    - name: Install boost
      uses: MarkusJx/install-boost@v2.4.1
      id: install_boost
      with:
        boost_version: 1.81.0