name: macos_clang_debug

on: push

jobs:
  macos_clang_debug:
    runs-on: macos-latest
    env:
      CXX: clang++

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/install_cmake
      - uses: ./.github/actions/install_dependencies
        with:
          build_type: Debug
      - uses: ./.github/actions/build
        with:
          build_type: Debug
      - uses: ./.github/actions/run_tests
      