name: macos_clang_release

on: push

jobs:
  macos_clang_release:
    runs-on: macos-latest
    env:
      CXX: clang++

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/linux/install_dependencies
        with:
          build_type: Release
      - uses: ./.github/actions/linux/build
        with:
          build_type: Release
      - uses: ./.github/actions/linux/run_tests
