name: macos_clang_debug

on:
  push:
    paths-ignore:
      - .clang-format
      - .gitignore
      - README.md

jobs:
  macos_clang_debug:
    runs-on: macos-latest
    env:
      CXX: clang++

    steps:
      - uses: actions/checkout@v2
      - id: install_dependencies
        uses: ./.github/actions/linux/install_dependencies
        with:
          build_type: Debug
      - uses: ./.github/actions/linux/build
        with:
          build_type: Debug
          BOOST_ROOT: ${{ steps.install_dependencies.outputs.BOOST_ROOT }}
      - uses: ./.github/actions/linux/run_tests
