name: ubuntu_gcc_debug

on: push

jobs:
  ubuntu_gcc_debug:
    runs-on: ubuntu-latest
    env:
      CXX: g++-10

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/linux/configure_gcc
      - uses: ./.github/actions/linux/install_cmake
      - uses: ./.github/actions/linux/install_dependencies
        with:
          build_type: Debug
      - uses: ./.github/actions/linux/build
        with:
          build_type: Debug
      - uses: ./.github/actions/linux/run_tests
      - uses: ./.github/actions/linux/calc_code_coverage
      