name: ubuntu_gcc_release

on: push

jobs:
  ubuntu_gcc_release:
    runs-on: ubuntu-latest
    env:
      CXX: g++-10

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/configure_gcc
      - uses: ./.github/actions/install_cmake
      - uses: ./.github/actions/install_dependencies
        with:
          build_type: Release
      - uses: ./.github/actions/build
        with:
          build_type: Release
      - uses: ./.github/actions/run_tests
      