name: ubuntu_gcc_debug

on:
  push:
    paths-ignore:
      - .clang-format
      - .gitignore
      - README.md

jobs:
  ubuntu_gcc_debug:
    runs-on: ubuntu-latest
    env:
      CXX: g++

    steps:
      - uses: actions/checkout@v2
      - uses: egor-tensin/setup-gcc@v1
        with:
          version: latest
          platform: x64
      - id: install_dependencies
        uses: ./.github/actions/linux/install_dependencies
        with:
          build_type: Debug
      - uses: ./.github/actions/linux/build
        with:
          build_type: Debug
          BOOST_ROOT: ${{ steps.install_dependencies.outputs.BOOST_ROOT }}
      - uses: ./.github/actions/linux/run_tests
      - uses: ./.github/actions/linux/calc_code_coverage