name: ubuntu_gcc_release

on: push

jobs:
  ubuntu_gcc_release:
    runs-on: ubuntu-latest
    env:
      CXX: g++

    steps:
      - uses: actions/checkout@v2
      - uses: egor-tensin/setup-gcc@v1
        with:
          version: 11
          platform: x64
      - id: install_dependencies
        uses: ./.github/actions/linux/install_dependencies
        with:
          build_type: Release
      - uses: ./.github/actions/linux/build
        with:
          build_type: Release
          BOOST_ROOT: ${{ steps.install_dependencies.outputs.BOOST_ROOT }}
      - uses: ./.github/actions/linux/run_tests
