name: ubuntu_clang_debug

on: push

jobs:
  ubuntu_clang_debug:
    runs-on: ubuntu-latest
    env:
      CXX: clang++-11

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/linux/configure_clang
      - uses: ./.github/actions/linux/install_cmake
      - uses: ./.github/actions/linux/install_dependencies
        with:
          build_type: Debug
      - uses: ./.github/actions/linux/build
        with:
          build_type: Debug
      - uses: ./.github/actions/linux/run_tests
      