name: ubuntu_clang_release

on: push

jobs:
  ubuntu_clang_release:
    runs-on: ubuntu-latest
    env:
      CXX: clang++

    steps:
      - uses: actions/checkout@v2
      - uses: KyleMayes/install-llvm-action@v1
        with:
          version: "14.0"
      - uses: ./.github/actions/linux/install_dependencies
        with:
          build_type: Release
      - uses: ./.github/actions/linux/build
        with:
          build_type: Release
      - uses: ./.github/actions/linux/run_tests
