name: ubuntu_clang_release

on:
  push:
    paths-ignore:
      - .clang-format
      - .gitignore
      - README.md

jobs:
  ubuntu_clang_release:
    runs-on: ubuntu-latest
    env:
      CXX: clang++

    steps:
      - uses: actions/checkout@v2
      - uses: KyleMayes/install-llvm-action@v2.0.7
        with:
          version: "20.1.3"
      - id: install_dependencies
        uses: ./.github/actions/linux/install_dependencies
        with:
          build_type: Release
      - uses: ./.github/actions/linux/build
        with:
          build_type: Release
          BOOST_ROOT: ${{ steps.install_dependencies.outputs.BOOST_ROOT }}
      - uses: ./.github/actions/linux/run_tests
