name: ubuntu_clang_release

on: push

jobs:
  ubuntu_clang_release:
    runs-on: ubuntu-latest
    env:
      CXX: clang++-11

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/linux/configure_clang
      - uses: ./.github/actions/linux/install_dependencies
        with:
          build_type: Release
      - uses: ./.github/actions/linux/build
        with:
          build_type: Release
      - uses: ./.github/actions/run_tests
        with:
          number_of_processors: $(nproc)