name: ubuntu_gcc_release

on: push

jobs:
  ubuntu_gcc_release:
    runs-on: ubuntu-latest
    env:
      CXX: g++-10

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/linux/configure_gcc
      - uses: ./.github/actions/linux/install_dependencies
        with:
          build_type: Release
      - uses: ./.github/actions/linux/build
        with:
          build_type: Release
      - uses: ./.github/actions/linux/run_tests
      