name: windows_msvc_release

on:
  push:
    paths-ignore:
      - .clang-format
      - .gitignore
      - README.md

jobs:
  windows_msvc_release:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - id: install_dependencies
        uses: ./.github/actions/windows/install_dependencies
        with:
          build_type: Release
          msvc_runtime_library: MultiThreaded
      - uses: ./.github/actions/windows/build
        with:
          build_type: Release
          BOOST_ROOT: ${{ steps.install_dependencies.outputs.BOOST_ROOT }}
      - uses: ./.github/actions/windows/run_tests
